version: "2"
run:
  tests: true
linters:
  enable:
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 100
    gocritic:
      enabled-checks:
        - ruleguard
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - depguard
          - dupl
          - errcheck
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - misspell
          - nakedret
          - prealloc
          - staticcheck
          - unconvert
          - unparam
          - unused
          - whitespace
        path: _test\.go
    paths:
      - \.gen\.go
      - \.pb\.go
      - vendor
      - .git
      - node_modules
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - \.gen\.go
      - \.pb\.go
      - vendor
      - .git
      - node_modules
      - third_party$
      - builtin$
      - examples$
      - _test\.go
