// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject/ent/project"
	"awesomeProject/ent/projectcolumn"
	"awesomeProject/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectColumnCreate is the builder for creating a ProjectColumn entity.
type ProjectColumnCreate struct {
	config
	mutation *ProjectColumnMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pcc *ProjectColumnCreate) SetName(s string) *ProjectColumnCreate {
	pcc.mutation.SetName(s)
	return pcc
}

// SetOrder sets the "order" field.
func (pcc *ProjectColumnCreate) SetOrder(i int) *ProjectColumnCreate {
	pcc.mutation.SetOrder(i)
	return pcc
}

// SetColor sets the "color" field.
func (pcc *ProjectColumnCreate) SetColor(s string) *ProjectColumnCreate {
	pcc.mutation.SetColor(s)
	return pcc
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (pcc *ProjectColumnCreate) AddTaskIDs(ids ...int) *ProjectColumnCreate {
	pcc.mutation.AddTaskIDs(ids...)
	return pcc
}

// AddTasks adds the "tasks" edges to the Task entity.
func (pcc *ProjectColumnCreate) AddTasks(t ...*Task) *ProjectColumnCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pcc.AddTaskIDs(ids...)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (pcc *ProjectColumnCreate) SetProjectID(id int) *ProjectColumnCreate {
	pcc.mutation.SetProjectID(id)
	return pcc
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (pcc *ProjectColumnCreate) SetNillableProjectID(id *int) *ProjectColumnCreate {
	if id != nil {
		pcc = pcc.SetProjectID(*id)
	}
	return pcc
}

// SetProject sets the "project" edge to the Project entity.
func (pcc *ProjectColumnCreate) SetProject(p *Project) *ProjectColumnCreate {
	return pcc.SetProjectID(p.ID)
}

// Mutation returns the ProjectColumnMutation object of the builder.
func (pcc *ProjectColumnCreate) Mutation() *ProjectColumnMutation {
	return pcc.mutation
}

// Save creates the ProjectColumn in the database.
func (pcc *ProjectColumnCreate) Save(ctx context.Context) (*ProjectColumn, error) {
	return withHooks(ctx, pcc.sqlSave, pcc.mutation, pcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *ProjectColumnCreate) SaveX(ctx context.Context) *ProjectColumn {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *ProjectColumnCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *ProjectColumnCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *ProjectColumnCreate) check() error {
	if _, ok := pcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProjectColumn.name"`)}
	}
	if v, ok := pcc.mutation.Name(); ok {
		if err := projectcolumn.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectColumn.name": %w`, err)}
		}
	}
	if _, ok := pcc.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "ProjectColumn.order"`)}
	}
	if _, ok := pcc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "ProjectColumn.color"`)}
	}
	if v, ok := pcc.mutation.Color(); ok {
		if err := projectcolumn.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "ProjectColumn.color": %w`, err)}
		}
	}
	return nil
}

func (pcc *ProjectColumnCreate) sqlSave(ctx context.Context) (*ProjectColumn, error) {
	if err := pcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pcc.mutation.id = &_node.ID
	pcc.mutation.done = true
	return _node, nil
}

func (pcc *ProjectColumnCreate) createSpec() (*ProjectColumn, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectColumn{config: pcc.config}
		_spec = sqlgraph.NewCreateSpec(projectcolumn.Table, sqlgraph.NewFieldSpec(projectcolumn.FieldID, field.TypeInt))
	)
	if value, ok := pcc.mutation.Name(); ok {
		_spec.SetField(projectcolumn.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pcc.mutation.Order(); ok {
		_spec.SetField(projectcolumn.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if value, ok := pcc.mutation.Color(); ok {
		_spec.SetField(projectcolumn.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if nodes := pcc.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectcolumn.TasksTable,
			Columns: []string{projectcolumn.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pcc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectcolumn.ProjectTable,
			Columns: []string{projectcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_columns = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectColumnCreateBulk is the builder for creating many ProjectColumn entities in bulk.
type ProjectColumnCreateBulk struct {
	config
	err      error
	builders []*ProjectColumnCreate
}

// Save creates the ProjectColumn entities in the database.
func (pccb *ProjectColumnCreateBulk) Save(ctx context.Context) ([]*ProjectColumn, error) {
	if pccb.err != nil {
		return nil, pccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*ProjectColumn, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectColumnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *ProjectColumnCreateBulk) SaveX(ctx context.Context) []*ProjectColumn {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *ProjectColumnCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *ProjectColumnCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
