// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject/ent/predicate"
	"awesomeProject/ent/project"
	"awesomeProject/ent/projectcolumn"
	"awesomeProject/ent/task"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectColumnQuery is the builder for querying ProjectColumn entities.
type ProjectColumnQuery struct {
	config
	ctx         *QueryContext
	order       []projectcolumn.OrderOption
	inters      []Interceptor
	predicates  []predicate.ProjectColumn
	withTasks   *TaskQuery
	withProject *ProjectQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectColumnQuery builder.
func (pcq *ProjectColumnQuery) Where(ps ...predicate.ProjectColumn) *ProjectColumnQuery {
	pcq.predicates = append(pcq.predicates, ps...)
	return pcq
}

// Limit the number of records to be returned by this query.
func (pcq *ProjectColumnQuery) Limit(limit int) *ProjectColumnQuery {
	pcq.ctx.Limit = &limit
	return pcq
}

// Offset to start from.
func (pcq *ProjectColumnQuery) Offset(offset int) *ProjectColumnQuery {
	pcq.ctx.Offset = &offset
	return pcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcq *ProjectColumnQuery) Unique(unique bool) *ProjectColumnQuery {
	pcq.ctx.Unique = &unique
	return pcq
}

// Order specifies how the records should be ordered.
func (pcq *ProjectColumnQuery) Order(o ...projectcolumn.OrderOption) *ProjectColumnQuery {
	pcq.order = append(pcq.order, o...)
	return pcq
}

// QueryTasks chains the current query on the "tasks" edge.
func (pcq *ProjectColumnQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: pcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectcolumn.Table, projectcolumn.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, projectcolumn.TasksTable, projectcolumn.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (pcq *ProjectColumnQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: pcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectcolumn.Table, projectcolumn.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectcolumn.ProjectTable, projectcolumn.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectColumn entity from the query.
// Returns a *NotFoundError when no ProjectColumn was found.
func (pcq *ProjectColumnQuery) First(ctx context.Context) (*ProjectColumn, error) {
	nodes, err := pcq.Limit(1).All(setContextOp(ctx, pcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectcolumn.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcq *ProjectColumnQuery) FirstX(ctx context.Context) *ProjectColumn {
	node, err := pcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectColumn ID from the query.
// Returns a *NotFoundError when no ProjectColumn ID was found.
func (pcq *ProjectColumnQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(1).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectcolumn.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcq *ProjectColumnQuery) FirstIDX(ctx context.Context) int {
	id, err := pcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectColumn entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectColumn entity is found.
// Returns a *NotFoundError when no ProjectColumn entities are found.
func (pcq *ProjectColumnQuery) Only(ctx context.Context) (*ProjectColumn, error) {
	nodes, err := pcq.Limit(2).All(setContextOp(ctx, pcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectcolumn.Label}
	default:
		return nil, &NotSingularError{projectcolumn.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcq *ProjectColumnQuery) OnlyX(ctx context.Context) *ProjectColumn {
	node, err := pcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectColumn ID in the query.
// Returns a *NotSingularError when more than one ProjectColumn ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcq *ProjectColumnQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(2).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectcolumn.Label}
	default:
		err = &NotSingularError{projectcolumn.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcq *ProjectColumnQuery) OnlyIDX(ctx context.Context) int {
	id, err := pcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectColumns.
func (pcq *ProjectColumnQuery) All(ctx context.Context) ([]*ProjectColumn, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryAll)
	if err := pcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectColumn, *ProjectColumnQuery]()
	return withInterceptors[[]*ProjectColumn](ctx, pcq, qr, pcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pcq *ProjectColumnQuery) AllX(ctx context.Context) []*ProjectColumn {
	nodes, err := pcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectColumn IDs.
func (pcq *ProjectColumnQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pcq.ctx.Unique == nil && pcq.path != nil {
		pcq.Unique(true)
	}
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryIDs)
	if err = pcq.Select(projectcolumn.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcq *ProjectColumnQuery) IDsX(ctx context.Context) []int {
	ids, err := pcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcq *ProjectColumnQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryCount)
	if err := pcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pcq, querierCount[*ProjectColumnQuery](), pcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pcq *ProjectColumnQuery) CountX(ctx context.Context) int {
	count, err := pcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcq *ProjectColumnQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryExist)
	switch _, err := pcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pcq *ProjectColumnQuery) ExistX(ctx context.Context) bool {
	exist, err := pcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectColumnQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcq *ProjectColumnQuery) Clone() *ProjectColumnQuery {
	if pcq == nil {
		return nil
	}
	return &ProjectColumnQuery{
		config:      pcq.config,
		ctx:         pcq.ctx.Clone(),
		order:       append([]projectcolumn.OrderOption{}, pcq.order...),
		inters:      append([]Interceptor{}, pcq.inters...),
		predicates:  append([]predicate.ProjectColumn{}, pcq.predicates...),
		withTasks:   pcq.withTasks.Clone(),
		withProject: pcq.withProject.Clone(),
		// clone intermediate query.
		sql:  pcq.sql.Clone(),
		path: pcq.path,
	}
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *ProjectColumnQuery) WithTasks(opts ...func(*TaskQuery)) *ProjectColumnQuery {
	query := (&TaskClient{config: pcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pcq.withTasks = query
	return pcq
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *ProjectColumnQuery) WithProject(opts ...func(*ProjectQuery)) *ProjectColumnQuery {
	query := (&ProjectClient{config: pcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pcq.withProject = query
	return pcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectColumn.Query().
//		GroupBy(projectcolumn.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pcq *ProjectColumnQuery) GroupBy(field string, fields ...string) *ProjectColumnGroupBy {
	pcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectColumnGroupBy{build: pcq}
	grbuild.flds = &pcq.ctx.Fields
	grbuild.label = projectcolumn.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ProjectColumn.Query().
//		Select(projectcolumn.FieldName).
//		Scan(ctx, &v)
func (pcq *ProjectColumnQuery) Select(fields ...string) *ProjectColumnSelect {
	pcq.ctx.Fields = append(pcq.ctx.Fields, fields...)
	sbuild := &ProjectColumnSelect{ProjectColumnQuery: pcq}
	sbuild.label = projectcolumn.Label
	sbuild.flds, sbuild.scan = &pcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectColumnSelect configured with the given aggregations.
func (pcq *ProjectColumnQuery) Aggregate(fns ...AggregateFunc) *ProjectColumnSelect {
	return pcq.Select().Aggregate(fns...)
}

func (pcq *ProjectColumnQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pcq); err != nil {
				return err
			}
		}
	}
	for _, f := range pcq.ctx.Fields {
		if !projectcolumn.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcq.path != nil {
		prev, err := pcq.path(ctx)
		if err != nil {
			return err
		}
		pcq.sql = prev
	}
	return nil
}

func (pcq *ProjectColumnQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectColumn, error) {
	var (
		nodes       = []*ProjectColumn{}
		withFKs     = pcq.withFKs
		_spec       = pcq.querySpec()
		loadedTypes = [2]bool{
			pcq.withTasks != nil,
			pcq.withProject != nil,
		}
	)
	if pcq.withProject != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, projectcolumn.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectColumn).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectColumn{config: pcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pcq.withTasks; query != nil {
		if err := pcq.loadTasks(ctx, query, nodes,
			func(n *ProjectColumn) { n.Edges.Tasks = []*Task{} },
			func(n *ProjectColumn, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := pcq.withProject; query != nil {
		if err := pcq.loadProject(ctx, query, nodes, nil,
			func(n *ProjectColumn, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pcq *ProjectColumnQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*ProjectColumn, init func(*ProjectColumn), assign func(*ProjectColumn, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProjectColumn)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(projectcolumn.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.project_column_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "project_column_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_column_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pcq *ProjectColumnQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ProjectColumn, init func(*ProjectColumn), assign func(*ProjectColumn, *Project)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProjectColumn)
	for i := range nodes {
		if nodes[i].project_columns == nil {
			continue
		}
		fk := *nodes[i].project_columns
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_columns" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pcq *ProjectColumnQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcq.querySpec()
	_spec.Node.Columns = pcq.ctx.Fields
	if len(pcq.ctx.Fields) > 0 {
		_spec.Unique = pcq.ctx.Unique != nil && *pcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pcq.driver, _spec)
}

func (pcq *ProjectColumnQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectcolumn.Table, projectcolumn.Columns, sqlgraph.NewFieldSpec(projectcolumn.FieldID, field.TypeInt))
	_spec.From = pcq.sql
	if unique := pcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pcq.path != nil {
		_spec.Unique = true
	}
	if fields := pcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectcolumn.FieldID)
		for i := range fields {
			if fields[i] != projectcolumn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcq *ProjectColumnQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcq.driver.Dialect())
	t1 := builder.Table(projectcolumn.Table)
	columns := pcq.ctx.Fields
	if len(columns) == 0 {
		columns = projectcolumn.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcq.sql != nil {
		selector = pcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcq.ctx.Unique != nil && *pcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pcq.predicates {
		p(selector)
	}
	for _, p := range pcq.order {
		p(selector)
	}
	if offset := pcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProjectColumnGroupBy is the group-by builder for ProjectColumn entities.
type ProjectColumnGroupBy struct {
	selector
	build *ProjectColumnQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcgb *ProjectColumnGroupBy) Aggregate(fns ...AggregateFunc) *ProjectColumnGroupBy {
	pcgb.fns = append(pcgb.fns, fns...)
	return pcgb
}

// Scan applies the selector query and scans the result into the given value.
func (pcgb *ProjectColumnGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcgb.build.ctx, ent.OpQueryGroupBy)
	if err := pcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectColumnQuery, *ProjectColumnGroupBy](ctx, pcgb.build, pcgb, pcgb.build.inters, v)
}

func (pcgb *ProjectColumnGroupBy) sqlScan(ctx context.Context, root *ProjectColumnQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pcgb.fns))
	for _, fn := range pcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pcgb.flds)+len(pcgb.fns))
		for _, f := range *pcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectColumnSelect is the builder for selecting fields of ProjectColumn entities.
type ProjectColumnSelect struct {
	*ProjectColumnQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pcs *ProjectColumnSelect) Aggregate(fns ...AggregateFunc) *ProjectColumnSelect {
	pcs.fns = append(pcs.fns, fns...)
	return pcs
}

// Scan applies the selector query and scans the result into the given value.
func (pcs *ProjectColumnSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcs.ctx, ent.OpQuerySelect)
	if err := pcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectColumnQuery, *ProjectColumnSelect](ctx, pcs.ProjectColumnQuery, pcs, pcs.inters, v)
}

func (pcs *ProjectColumnSelect) sqlScan(ctx context.Context, root *ProjectColumnQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pcs.fns))
	for _, fn := range pcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
