// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject/ent/subtask"
	"awesomeProject/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubtaskCreate is the builder for creating a Subtask entity.
type SubtaskCreate struct {
	config
	mutation *SubtaskMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (sc *SubtaskCreate) SetTitle(s string) *SubtaskCreate {
	sc.mutation.SetTitle(s)
	return sc
}

// SetDescription sets the "description" field.
func (sc *SubtaskCreate) SetDescription(s string) *SubtaskCreate {
	sc.mutation.SetDescription(s)
	return sc
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (sc *SubtaskCreate) SetTaskID(id int) *SubtaskCreate {
	sc.mutation.SetTaskID(id)
	return sc
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (sc *SubtaskCreate) SetNillableTaskID(id *int) *SubtaskCreate {
	if id != nil {
		sc = sc.SetTaskID(*id)
	}
	return sc
}

// SetTask sets the "task" edge to the Task entity.
func (sc *SubtaskCreate) SetTask(t *Task) *SubtaskCreate {
	return sc.SetTaskID(t.ID)
}

// Mutation returns the SubtaskMutation object of the builder.
func (sc *SubtaskCreate) Mutation() *SubtaskMutation {
	return sc.mutation
}

// Save creates the Subtask in the database.
func (sc *SubtaskCreate) Save(ctx context.Context) (*Subtask, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubtaskCreate) SaveX(ctx context.Context) *Subtask {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubtaskCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubtaskCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubtaskCreate) check() error {
	if _, ok := sc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Subtask.title"`)}
	}
	if _, ok := sc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Subtask.description"`)}
	}
	if v, ok := sc.mutation.Description(); ok {
		if err := subtask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Subtask.description": %w`, err)}
		}
	}
	return nil
}

func (sc *SubtaskCreate) sqlSave(ctx context.Context) (*Subtask, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubtaskCreate) createSpec() (*Subtask, *sqlgraph.CreateSpec) {
	var (
		_node = &Subtask{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subtask.Table, sqlgraph.NewFieldSpec(subtask.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Title(); ok {
		_spec.SetField(subtask.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := sc.mutation.Description(); ok {
		_spec.SetField(subtask.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := sc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtask.TaskTable,
			Columns: []string{subtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_subtasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubtaskCreateBulk is the builder for creating many Subtask entities in bulk.
type SubtaskCreateBulk struct {
	config
	err      error
	builders []*SubtaskCreate
}

// Save creates the Subtask entities in the database.
func (scb *SubtaskCreateBulk) Save(ctx context.Context) ([]*Subtask, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subtask, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubtaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubtaskCreateBulk) SaveX(ctx context.Context) []*Subtask {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubtaskCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubtaskCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
