name: Embassy-monitoring pipeline
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
env:
  GOLANGCI_LINT_VERSION: v2.0.2

jobs:
  lint-golangci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ env.BRANCH }}

  build:
    runs-on: ubuntu-22.04
    needs: lint-golangci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run tests
        run: go test ./... -tags=unit
      - name: Build
        run: go build ./...